// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzkvnoexnbbaokxtlopc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6a3Zub2V4bmJiYW9reHRsb3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzQzMDUsImV4cCI6MjA2NzQxMDMwNX0.cdt9F3zHWq_JsG9WD78R5PdFpw4bUslfv5BM83n-lQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});